spring.application.name: EstateRunner

server.port: 7090

database.url: jdbc:mysql://localhost:3310

spring:
  datasource:
    url: ${database.url}/estaterunner?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&serverTimezone=Africa/Lagos
    username: root
    password: admin1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      show-sql: true
      proc:
        param_null_passing: true

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO


  kafka:
    bootstrap-servers: localhost:9040
    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: NIL
      security:
        protocol: PLAINTEXT


server.max-http-header-size: 52428800
multipart.max-file-size: 5MB
multipart.max-request-size: 5MB


logging:
  level.ROOT: INFO

logging.level.org.springframework.messaging: DEBUG


redis.host: localhost
redis.port: '6379'
redis.database: 2
redis.password: '8hZa8Aamri'
spring.redis.password: '8hZa8Aamri'
redis.default.expiry: 86400
redis.connection.timeout: 5000
jedis.config.max.total: 1000
jedis.config.max.idle: 10
jedis.config.max.wait.millis: 500
jedis.config.test.on.borrow: true
jedis.config.test.on.return: true
jedis.config.test.while.idle: true
jedis.config.num.tests.per.eviction.run: 10
redisson.config.cluster.mode: false
redisson.config.override: true
